### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by sjqqka** [yiranran/Unpaired-Portrait-Drawing#18]
你好，我按照requirements配了环境，下载了pre-trained model，执行了readme里的测试代码，但是没有result文件夹生成，如果用test.py测试的话您知道应该用什么代码吗，因为好像涉及很多需要设定的--

**Comment by sjqqka** [comment]
以及一定要在linux里运行吗，windows可以吗

**Comment by yiranran** [comment]
您好我们是在linux运行的，windows有pytorch环境应该也可以的，不过我们没有测试过

**Comment by yiranran** [comment]
您可以尝试我们提供的google colab运行 [Colab demo](https://colab.research.google.com/drive/1U1fPXD1JukuKPOrhGMX1iaJC-d8_RUYr)
