### ISSUE TITLE
About preprocessing

### ISSUE THREAD

**Issue by guligualagulu** [yiranran/Unpaired-Portrait-Drawing#19]
I need your help!

Who can tell me how to use the face parsing network in https://github.com/cientgu/Mask_Guided_Portrait_Editing?

Looking forward to reply!

**Comment by yiranran** [comment]
Hi, here is a script we used to generate face parsing maps. We put it in the folder of "Mask_Guided_Portrait_Editing".
https://drive.google.com/file/d/1ZBuiro9pVU1anGHO9UwHK0mdbsuY-dv6/view?usp=sharing
