### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by AdamGustavsson** [yiranran/Unpaired-Portrait-Drawing#2]
Your project looks awesome. Thanks for releasing it. It would be great if you mad a Colab file (and link to it in the readme) as an example so that less tech savvy people could play around with it.

**Comment by yiranran** [comment]
https://colab.research.google.com/drive/1U1fPXD1JukuKPOrhGMX1iaJC-d8_RUYr
Is this one okay?

**Comment by AdamGustavsson** [comment]
Thanks! 
That was great.
I had to add a cd like this:
%cd Unpaired-Portrait-Drawing
!python test_seq_style.py
in order for it to run for me. Perhaps you should change that.

**Comment by yiranran** [comment]
Thank you~ I’ve changed that.
