### ISSUE TITLE
learning rate is 0.000015？

### ISSUE THREAD

**Issue by HUSTLX** [yiranran/Unpaired-Portrait-Drawing#4]
usually the learnling rate is 0.0002，why do you use 0.000015？is there a clear experimental proof？

**Comment by yiranran** [comment]
When we use the style vec as additional input, we found using 2e-4 would lead the network to diverge…
So we lower the learning rate to … to 2e-5 and then to 1.5e-5… 
Experiments show 1.5e-5 gets better results.
