### ISSUE TITLE
checkpoints/weights/v0.1/alex.pth is unavilable

### ISSUE THREAD

**Issue by HUSTLX** [yiranran/Unpaired-Portrait-Drawing#6]
checkpoints/weights/v0.1/alex.pth is unavilable

**Comment by yiranran** [comment]
@HUSTLX  sorry, I did not upload the models needed in the training, i.e. for HED and LPIPS calculation. 
I have uploaded them to the baiduyun and google drive now.

Also I cannot make the training set public because of copyright problems.
