### ISSUE TITLE
TypeError: only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by luoww1992** [yiranran/Unpaired-Portrait-Drawing#9]
when i use the default model and images to run the code ,  i get this error attrntion ? 
how to do we need ?

**Comment by ChauvinisticJonatha** [comment]
Have you solved it? The same problem with APDrawinggan in his warehouse.

**Comment by yiranran** [comment]
Sorry, this error is because the original version is run using python2
Please check can this commit of APDrawingGAN to solve your problem? https://github.com/yiranran/APDrawingGAN/commit/bc10583a244620325c6e4874566112ebbf5d2c7d
